### ISSUE TITLE
Something wrong with the disclaimer link on login form

### ISSUE THREAD

**Issue by kreynen** [KyleRosenberg/CourseScheduler#34]
Overall this is very impressive.  I'm seeing an `Popup: Popup does not fit within the boundaries of the viewport` error when trying to see the disclaimer about what you doing with student Identikeys. 

https://github.com/KyleRosenberg/CourseScheduler/blob/2c1d5674feebc4d4e8668e280ba3df4aa030155f/templates/classsearch.html#L361

Even with that disclaimer, I'm not sure this isn't going to get shut down by CU's security team once they notice it. I've reached out via email.  Let's talk.

**Comment by KyleRosenberg** [comment]
Fixed in https://github.com/KyleRosenberg/CourseScheduler/pull/35/commits/183b9678ba86713e0e235b1e9b83d7b3f383e46a
